name: Deploy

env:
  DEPLOY_URL: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}

on:
    pull_request:
      types: 
        - closed
      branches:
        - main
       
jobs:
    ci:
      runs-on: ubuntu-latest
      steps: 
        - name: Deploy
          run: |
            curl "$DEPLOY_URL"