name: Deploy

env:
  DEPLOY_URL: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}

on:
    pull_request:
      types: 
        - closed
      branches:
        - main
       
jobs:
    ci:
      name: Deploy to Render
      runs-on: ubuntu-latest
      steps: 
        - name: Checkout Code
          uses: actions/checkout@v1

          name: Install dependencies
          run: npm install
          
          name: Deply
          if: github.ref == 'refs/heads/main'
          
          run: |
            curl "$DEPLOY_URL"