name: Deploy

on:
    push:
      branches: [main, feat/deploy-hook] 
    pull_request:
      branches:
        - main
        - feat/deploy-hook
       
jobs:
    ci:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3

        - name: Instal dependencies
          run: |
            npm install

        - name: Start server and client
          run: npm run develop &

        - name: Wait for server to be ready
          run: npx wait-on http://localhost:3001

        - name: Run tests
          run: npm run test

        - name: Deploy
          if: github.ref == 'refs/heads/main'
          env:
            DEPLOY_URL: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
          run: |
            curl "$DEPLOY_URL"