# # Name of workflow
name: Cypress Tests

# # Trigger workflow on all pull requests
on:
  pull_request:
    branches:
      - develop
      - staging

# # Jobs to carry out
jobs:
  cypress:
    # Operating system to run job on
    runs-on: ubuntu-latest

    # Steps in job
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js 21.x
        uses: actions/setup-node@v2
        with:
          node-version: 21.x

      - name: Install dependencies
        run: npm i

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with: 
          build: npm run build
          start: npm run start
