# # Name of workflow
# name: Cypress Tests

# # Trigger workflow on all pull requests
# on:
#   pull_request:
#     branches:
#       - develop
#       - staging

# # Jobs to carry out
# jobs:
#   cypress:
#     # Operating system to run job on
#     runs-on: ubuntu-latest

#     # Steps in job
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v2

#       - name: Use Node.js 21.x
#         uses: actions/setup-node@v2
#         with:
#           node-version: 21.x

#       # Install dependencies
#       - name: 🧰 Install Deps
#         run: npm install
        
#       # Run Cypress
#       - name: Run Cypress tests
#         run: npm run test

#       # Run build
#       - name: Run Build
#         run: npm run build